{% set version = "0.4.1" %}

package:
  name: lsstdesc-wl-shear-sims
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/descwl-shear-sims/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5c99d9cd8c6714d95e9f49232a0c10283c19ecc2ff2c3c1138818fafd5b868c5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.10
    - setuptools >=38
    - pip
  run:
    - python >=3.10
    - numba
    - lsstdesc.weaklensingdeblending
    - pydantic
    - hexalattice

test:
  imports:
    - descwl_shear_sims
  requires:
    - stackvana

about:
  home: https://github.com/LSSTDESC/descwl-shear-sims/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "DESC weal lensing shear simulations"
  description: |
    descwl-shear-sims is a open-source package to simulate galaxy images for
    shear related tests
extra:
  recipe-maintainers:
    - mr-superonion
    - beckermr
