{% set python_min = "3.10" %}
{% set version = "0.4.5" %}

package:
  name: lsstdesc-wl-shear-sims
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/descwl-shear-sims/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 91235ffd4d39455c231f5abb645872860182209021a421f53d53b88fb2548b1f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=38
    - pip
  run:
    - python >={{ python_min }}
    - numba
    - lsstdesc.weaklensingdeblending
    - pydantic
    - hexalattice
    - lenstronomy

test:
  imports:
    - descwl_shear_sims
  requires:
    - stackvana
    - python {{ python_min }}

about:
  home: https://github.com/LSSTDESC/descwl-shear-sims/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "DESC weal lensing shear simulations"
  description: |
    descwl-shear-sims is a open-source package to simulate galaxy images for
    shear related tests
extra:
  recipe-maintainers:
    - mr-superonion
    - beckermr
